// src/mockData/tasks.js
// Synthetic Unified Maintenance Tasks across Engineering, S&T, and Traction

export const mockTasks = [
  {
    id: "ENG-2031",
    department: "Engineering",
    corridor: "NDLS-CNB",
    corridorName: "New Delhi - Kanpur Central (Line 1)",
    sourceSystem: "TMS",
    taskType: "Rail Fracture Repair & Ultrasonic Testing",
    assetId: "TRK-CNB-104-UP",
    criticality: "Critical",
    defectSeverity: 88, // 0-100
    urgency: 92,
    failureRiskScore: 0.85, // 0-1
    overdueDays: 14,
    assetAvailabilityImpact: 85, // 0-100
    estimatedDurationMins: 90,
    requiredResources: "Heavy Tamper #3, Rail Gang 12, USFD Trolley",
    safetyRequirements: {
      powerOff: true,
      isolation: "Full Sectional",
      speedRestriction: "20 km/h Post-Work"
    },
    requestedWindow: { date: "2026-09-05", start: "07:00", end: "08:30" },
    priorityScore: 91, // AI Output
    priorityBand: "Critical",
    priorityFactors: {
      criticality: 22,
      urgency: 20,
      defectSeverity: 24,
      failureRisk: 14,
      overdue: 11,
      availabilityImpact: 10
    },
    aiJustification: "Critical Priority (91/100): High defect severity (88) with imminent fracture risk on high-speed NDLS-CNB corridor. Task is 14 days overdue and poses severe derailment hazard if unaddressed."
  },
  {
    id: "SNT-1187",
    department: "S&T",
    corridor: "NDLS-CNB",
    corridorName: "New Delhi - Kanpur Central (Line 1)",
    sourceSystem: "SMMS",
    taskType: "Point Machine Overhaul & Relay Testing",
    assetId: "SIG-SW-42A",
    criticality: "High",
    defectSeverity: 74,
    urgency: 78,
    failureRiskScore: 0.68,
    overdueDays: 8,
    assetAvailabilityImpact: 65,
    estimatedDurationMins: 75,
    requiredResources: "Signal Testing Kit, Telecom Gang 04, Relay Calibrator",
    safetyRequirements: {
      powerOff: false,
      isolation: "Interlocking Disconnection",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-05", start: "07:30", end: "08:45" },
    priorityScore: 78,
    priorityBand: "High",
    priorityFactors: {
      criticality: 18,
      urgency: 16,
      defectSeverity: 19,
      failureRisk: 11,
      overdue: 8,
      availabilityImpact: 6
    },
    aiJustification: "High Priority (78/100): Point machine switch 42A showing irregular contact resistance. 8 days overdue for bi-monthly overhaul; high correlation with route locking delays."
  },
  {
    id: "TRC-0552",
    department: "Traction",
    corridor: "NDLS-CNB",
    corridorName: "New Delhi - Kanpur Central (Line 1)",
    sourceSystem: "TDMS",
    taskType: "OHE Insulator Cleaning & Contact Wire Dropper Replacement",
    assetId: "OHE-MAST-819",
    criticality: "High",
    defectSeverity: 76,
    urgency: 72,
    failureRiskScore: 0.71,
    overdueDays: 10,
    assetAvailabilityImpact: 70,
    estimatedDurationMins: 90,
    requiredResources: "Tower Wagon TW-08, OHE Linesmen Team 2, Discharge Rods",
    safetyRequirements: {
      powerOff: true,
      isolation: "25kV Traction Power Shutoff",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-05", start: "08:00", end: "09:30" },
    priorityScore: 79,
    priorityBand: "High",
    priorityFactors: {
      criticality: 19,
      urgency: 15,
      defectSeverity: 20,
      failureRisk: 12,
      overdue: 7,
      availabilityImpact: 6
    },
    aiJustification: "High Priority (79/100): Flashover marks detected on porcelain bracket insulators. Requires 25kV power block; bundling with track possessions will prevent independent line shutdowns."
  },
  {
    id: "ENG-2045",
    department: "Engineering",
    corridor: "HWH-MGS",
    corridorName: "Howrah - Pt. Deen Dayal Upadhyaya (Line 2)",
    sourceSystem: "TMS",
    taskType: "Ballast Deep Screening & Tamping",
    assetId: "TRK-HWH-512-DN",
    criticality: "High",
    defectSeverity: 80,
    urgency: 75,
    failureRiskScore: 0.74,
    overdueDays: 18,
    assetAvailabilityImpact: 60,
    estimatedDurationMins: 150,
    requiredResources: "BCM Machine 09, Ballast Hopper Train, Track Machine Gang",
    safetyRequirements: {
      powerOff: true,
      isolation: "Full Sectional",
      speedRestriction: "30 km/h Caution"
    },
    requestedWindow: { date: "2026-09-06", start: "01:30", end: "04:00" },
    priorityScore: 84,
    priorityBand: "Critical",
    priorityFactors: {
      criticality: 20,
      urgency: 18,
      defectSeverity: 22,
      failureRisk: 12,
      overdue: 8,
      availabilityImpact: 4
    },
    aiJustification: "Critical Priority (84/100): Severe ballast fouling causing track geometry degradation. 18 days overdue; requires urgent screening to prevent emergency caution orders."
  },
  {
    id: "SNT-1192",
    department: "S&T",
    corridor: "HWH-MGS",
    corridorName: "Howrah - Pt. Deen Dayal Upadhyaya (Line 2)",
    sourceSystem: "SMMS",
    taskType: "Axle Counter Replacement & Cable Jointing",
    assetId: "SIG-AXC-108",
    criticality: "Medium",
    defectSeverity: 58,
    urgency: 55,
    failureRiskScore: 0.45,
    overdueDays: 4,
    assetAvailabilityImpact: 50,
    estimatedDurationMins: 60,
    requiredResources: "Digital Axle Tester, S&T Technician Squad",
    safetyRequirements: {
      powerOff: false,
      isolation: "Disconnection Notice",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-06", start: "02:00", end: "03:00" },
    priorityScore: 56,
    priorityBand: "Medium",
    priorityFactors: {
      criticality: 12,
      urgency: 11,
      defectSeverity: 14,
      failureRisk: 8,
      overdue: 6,
      availabilityImpact: 5
    },
    aiJustification: "Medium Priority (56/100): Intermittent track detection glitches logged during peak humidity. Can be safely co-scheduled with corridor possession."
  },
  {
    id: "TRC-0561",
    department: "Traction",
    corridor: "HWH-MGS",
    corridorName: "Howrah - Pt. Deen Dayal Upadhyaya (Line 2)",
    sourceSystem: "TDMS",
    taskType: "Substation Circuit Breaker Maintenance",
    assetId: "TSS-MGS-CB02",
    criticality: "High",
    defectSeverity: 72,
    urgency: 68,
    failureRiskScore: 0.65,
    overdueDays: 6,
    assetAvailabilityImpact: 80,
    estimatedDurationMins: 120,
    requiredResources: "SF6 Gas Analyzer, Traction Substation Crew",
    safetyRequirements: {
      powerOff: true,
      isolation: "Grid Feeder Isolation",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-06", start: "02:00", end: "04:00" },
    priorityScore: 74,
    priorityBand: "High",
    priorityFactors: {
      criticality: 17,
      urgency: 14,
      defectSeverity: 18,
      failureRisk: 11,
      overdue: 7,
      availabilityImpact: 7
    },
    aiJustification: "High Priority (74/100): Traction Substation SF6 gas pressure near warning threshold. Critical for 25kV power feed stability across 60km section."
  },
  {
    id: "ENG-2052",
    department: "Engineering",
    corridor: "BCT-BRC",
    corridorName: "Mumbai Central - Vadodara (Western Line)",
    sourceSystem: "TMS",
    taskType: "Turnout Sleeper Renewal",
    assetId: "TRK-BRC-TO-19",
    criticality: "High",
    defectSeverity: 68,
    urgency: 62,
    failureRiskScore: 0.58,
    overdueDays: 9,
    assetAvailabilityImpact: 55,
    estimatedDurationMins: 110,
    requiredResources: "UNIMAT Tamping Machine, Track Gang 07",
    safetyRequirements: {
      powerOff: true,
      isolation: "Sectional",
      speedRestriction: "15 km/h Caution"
    },
    requestedWindow: { date: "2026-09-07", start: "00:30", end: "02:30" },
    priorityScore: 71,
    priorityBand: "High",
    priorityFactors: {
      criticality: 16,
      urgency: 13,
      defectSeverity: 17,
      failureRisk: 11,
      overdue: 8,
      availabilityImpact: 6
    },
    aiJustification: "High Priority (71/100): Turnout sleeper cracking exceeding permissible wear limit. Scheduled during night freight slack window."
  },
  {
    id: "SNT-1205",
    department: "S&T",
    corridor: "BCT-BRC",
    corridorName: "Mumbai Central - Vadodara (Western Line)",
    sourceSystem: "SMMS",
    taskType: "Kavach ATP Trackside Unit Diagnostic",
    assetId: "ATP-TCAS-BRC-04",
    criticality: "Critical",
    defectSeverity: 82,
    urgency: 86,
    failureRiskScore: 0.79,
    overdueDays: 5,
    assetAvailabilityImpact: 75,
    estimatedDurationMins: 60,
    requiredResources: "Kavach Specialist Unit, RF Calibration Mast",
    safetyRequirements: {
      powerOff: false,
      isolation: "Signaling Bypass",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-07", start: "01:00", end: "02:00" },
    priorityScore: 86,
    priorityBand: "Critical",
    priorityFactors: {
      criticality: 21,
      urgency: 19,
      defectSeverity: 21,
      failureRisk: 13,
      overdue: 6,
      availabilityImpact: 6
    },
    aiJustification: "Critical Priority (86/100): Trackside Kavach RFID reader intermittently failing balise ping. Safety-critical for automatic train protection at 160 km/h."
  },
  {
    id: "TRC-0578",
    department: "Traction",
    corridor: "BCT-BRC",
    corridorName: "Mumbai Central - Vadodara (Western Line)",
    sourceSystem: "TDMS",
    taskType: "Cantilever Assembly Realignment",
    assetId: "OHE-CANT-331",
    criticality: "Medium",
    defectSeverity: 52,
    urgency: 48,
    failureRiskScore: 0.40,
    overdueDays: 3,
    assetAvailabilityImpact: 45,
    estimatedDurationMins: 75,
    requiredResources: "Tower Wagon TW-02, Linemen Team",
    safetyRequirements: {
      powerOff: true,
      isolation: "25kV Power Shutoff",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-07", start: "01:00", end: "02:15" },
    priorityScore: 52,
    priorityBand: "Medium",
    priorityFactors: {
      criticality: 11,
      urgency: 10,
      defectSeverity: 13,
      failureRisk: 8,
      overdue: 5,
      availabilityImpact: 5
    },
    aiJustification: "Medium Priority (52/100): Minor stagger variation in contact wire. High compatibility with Kavach and Turnout work on same section."
  },
  {
    id: "ENG-2060",
    department: "Engineering",
    corridor: "MAS-RU",
    corridorName: "Chennai Central - Renigunta (South Central)",
    sourceSystem: "TMS",
    taskType: "Flash Butt Rail Welding",
    assetId: "TRK-MAS-WELD-88",
    criticality: "High",
    defectSeverity: 70,
    urgency: 65,
    failureRiskScore: 0.62,
    overdueDays: 11,
    assetAvailabilityImpact: 65,
    estimatedDurationMins: 120,
    requiredResources: "Mobile Flash Butt Welding Plant, Welders Guild",
    safetyRequirements: {
      powerOff: true,
      isolation: "Full Sectional",
      speedRestriction: "30 km/h"
    },
    requestedWindow: { date: "2026-09-08", start: "11:00", end: "13:00" },
    priorityScore: 73,
    priorityBand: "High",
    priorityFactors: {
      criticality: 16,
      urgency: 14,
      defectSeverity: 18,
      failureRisk: 11,
      overdue: 8,
      availabilityImpact: 6
    },
    aiJustification: "High Priority (73/100): Eliminating fishplated joints on heavy axle load freight route. 11 days overdue."
  },
  {
    id: "SNT-1218",
    department: "S&T",
    corridor: "MAS-RU",
    corridorName: "Chennai Central - Renigunta (South Central)",
    sourceSystem: "SMMS",
    taskType: "Electronic Interlocking (EI) Diagnostic & Card Swap",
    assetId: "SIG-EI-RU-02",
    criticality: "Critical",
    defectSeverity: 85,
    urgency: 88,
    failureRiskScore: 0.81,
    overdueDays: 7,
    assetAvailabilityImpact: 90,
    estimatedDurationMins: 90,
    requiredResources: "OEM Systems Engineer, Signal Inspection Team",
    safetyRequirements: {
      powerOff: false,
      isolation: "Station Interlocking Disconnection",
      speedRestriction: "Non-Interlocked (15 km/h)"
    },
    requestedWindow: { date: "2026-09-08", start: "11:30", end: "13:00" },
    priorityScore: 89,
    priorityBand: "Critical",
    priorityFactors: {
      criticality: 22,
      urgency: 19,
      defectSeverity: 22,
      failureRisk: 14,
      overdue: 6,
      availabilityImpact: 6
    },
    aiJustification: "Critical Priority (89/100): Redundancy failover alert triggered in Standby Central Processing Card. Requires immediate controlled possession."
  },
  {
    id: "TRC-0590",
    department: "Traction",
    corridor: "MAS-RU",
    corridorName: "Chennai Central - Renigunta (South Central)",
    sourceSystem: "TDMS",
    taskType: "Section Insulator Gap Adjustment",
    assetId: "OHE-SI-114",
    criticality: "Medium",
    defectSeverity: 48,
    urgency: 42,
    failureRiskScore: 0.35,
    overdueDays: 2,
    assetAvailabilityImpact: 40,
    estimatedDurationMins: 60,
    requiredResources: "Ladder Trolley, Linemen Squad 3",
    safetyRequirements: {
      powerOff: true,
      isolation: "Elementary Section Power Block",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-08", start: "12:00", end: "13:00" },
    priorityScore: 47,
    priorityBand: "Medium",
    priorityFactors: {
      criticality: 10,
      urgency: 9,
      defectSeverity: 12,
      failureRisk: 7,
      overdue: 5,
      availabilityImpact: 4
    },
    aiJustification: "Medium Priority (47/100): Routine tolerance adjustment on neutral section runner assembly."
  },
  {
    id: "ENG-2077",
    department: "Engineering",
    corridor: "SBC-JTJ",
    corridorName: "KSR Bengaluru - Jolarpettai (South Western)",
    sourceSystem: "TMS",
    taskType: "Track De-stressing in Curve 14",
    assetId: "TRK-SBC-CURVE-14",
    criticality: "Low",
    defectSeverity: 32,
    urgency: 28,
    failureRiskScore: 0.22,
    overdueDays: 0,
    assetAvailabilityImpact: 30,
    estimatedDurationMins: 180,
    requiredResources: "Tensor Equipment, Gas Cutters, Track Men",
    safetyRequirements: {
      powerOff: false,
      isolation: "Full Sectional",
      speedRestriction: "30 km/h"
    },
    requestedWindow: { date: "2026-09-09", start: "14:00", end: "17:00" },
    priorityScore: 34,
    priorityBand: "Low",
    priorityFactors: {
      criticality: 7,
      urgency: 6,
      defectSeverity: 9,
      failureRisk: 5,
      overdue: 4,
      availabilityImpact: 3
    },
    aiJustification: "Low Priority (34/100): Preventative thermal rail adjustment ahead of seasonal temperature shifts. No immediate safety defect."
  },
  {
    id: "SNT-1229",
    department: "S&T",
    corridor: "SBC-JTJ",
    corridorName: "KSR Bengaluru - Jolarpettai (South Western)",
    sourceSystem: "SMMS",
    taskType: "LED Signal Unit Luminescence Check",
    assetId: "SIG-LAMP-SBC-12",
    criticality: "Low",
    defectSeverity: 25,
    urgency: 20,
    failureRiskScore: 0.15,
    overdueDays: 0,
    assetAvailabilityImpact: 20,
    estimatedDurationMins: 45,
    requiredResources: "Lux Meter, S&T Patrolman",
    safetyRequirements: {
      powerOff: false,
      isolation: "None",
      speedRestriction: "None"
    },
    requestedWindow: { date: "2026-09-09", start: "15:00", end: "15:45" },
    priorityScore: 26,
    priorityBand: "Low",
    priorityFactors: {
      criticality: 5,
      urgency: 5,
      defectSeverity: 7,
      failureRisk: 3,
      overdue: 3,
      availabilityImpact: 3
    },
    aiJustification: "Low Priority (26/100): Routine quarterly lux rating measurement on home signal aspects."
  }
];
