// src/components/common/DisclaimerPill.jsx
import React from 'react';
import { Sparkles, Info } from 'lucide-react';

export const DisclaimerPill = ({ text = "AI Recommendation", variant = "ai" }) => {
  if (variant === 'synthetic') {
    return (
      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-medium bg-slate-100 text-slate-600 border border-slate-200" title="Synthetic prototype data for SIH PS 26027">
        <Info className="w-3 h-3 text-slate-500" />
        <span>{text}</span>
      </span>
    );
  }

  return (
    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-medium bg-sky-50 text-sky-800 border border-sky-200" title="Generated by AI Decision Engine">
      <Sparkles className="w-3 h-3 text-sky-600" />
      <span>{text}</span>
    </span>
  );
};
